name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-10

    steps:
      - uses: actions/checkout@v2

      - name: Build app
        run: msbuild SmartOpt.sln /p:Configuration=Release /p:TargetFrameworkVersion=v3.5

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SmartOpt
          path: publish
